# Generated by Django 4.1.1 on 2022-10-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.IntegerField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STD", "base employee"),
                            ("MGR", "manager"),
                            ("SRMGR", "senior manager"),
                            ("PRES", "president"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "manager_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.person",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="staff", name="manager_id",),
        migrations.RemoveField(model_name="staff", name="user",),
        migrations.DeleteModel(name="Customers",),
        migrations.DeleteModel(name="Staff",),
    ]
